LIMITLESS_BASE_URL = "https://play.limitlesstcg.com"
DEFAULT_GAME_CODE = "POCKET"
LIMITLESS_DECKS_URL = f"{LIMITLESS_BASE_URL}/decks?game={DEFAULT_GAME_CODE}"

__all__ = ["DEFAULT_GAME_CODE", "LIMITLESS_BASE_URL", "LIMITLESS_DECKS_URL"]
